# Generated by Django 4.2.5 on 2024-01-17 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmPrediction',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('gameweek', models.PositiveIntegerField(default=1)),
                ('scores', models.JSONField(default=dict)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('isscorecomplete', models.BooleanField(default=False)),
                ('predictionscore', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIresponses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateField(default=django.utils.timezone.now)),
                ('fantasty_api', models.JSONField(default=dict)),
                ('fbmatch_api', models.JSONField(default=dict)),
                ('fbstanding_api', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='PremCompetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField()),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('emblem', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PremSeasonInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('currentMatchday', models.PositiveIntegerField(default=1)),
                ('winner', models.CharField(default='null')),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PremTeams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField()),
                ('shortname', models.CharField()),
                ('initals', models.CharField()),
                ('badge', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('createnum', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='')),
                ('avatar', models.CharField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('gameweek', models.PositiveIntegerField(default=1)),
                ('scores', models.JSONField(default=dict)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('isscorecomplete', models.BooleanField(default=False)),
                ('predictionscore', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremTable',
            fields=[
                ('position', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('played', models.PositiveIntegerField(default=0)),
                ('win', models.PositiveIntegerField(default=0)),
                ('draw', models.PositiveIntegerField(default=0)),
                ('loss', models.PositiveIntegerField(default=0)),
                ('goaldifference', models.FloatField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prempredict.premseasoninfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prempredict.premteams')),
            ],
        ),
        migrations.CreateModel(
            name='PremGameweeks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='')),
                ('number', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prempredict.premseasoninfo')),
            ],
        ),
        migrations.CreateModel(
            name='PremGames',
            fields=[
                ('matchid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_name', models.CharField()),
                ('area_code', models.CharField()),
                ('area_flag', models.CharField()),
                ('status', models.CharField(default='')),
                ('score_winner', models.CharField()),
                ('score_duration', models.CharField()),
                ('score_hometeam', models.PositiveIntegerField()),
                ('score_awayteam', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('matchday', models.PositiveIntegerField()),
                ('awayteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixture', to='prempredict.premteams')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prempredict.premcompetition')),
                ('hometeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixture', to='prempredict.premteams')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prempredict.premseasoninfo')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('createnum', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
    ]
