# Generated by Django 4.2.5 on 2024-01-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILeaderboard',
            fields=[
                ('createnum', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
