# Generated by Django 4.2.5 on 2024-01-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0002_aileaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='aileaderboard',
            name='getval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
