# Generated by Django 4.2.5 on 2024-01-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0003_aileaderboard_getval'),
    ]

    operations = [
        migrations.AddField(
            model_name='aileaderboard',
            name='average_gw_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aileaderboard',
            name='completed_gw_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aileaderboard',
            name='correct_accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aileaderboard',
            name='result_accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='average_gw_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='completed_gw_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='correct_accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='result_accuracy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
