# Generated by Django 4.2.5 on 2024-01-19 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0004_aileaderboard_average_gw_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmprediction',
            name='score_check_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprediction',
            name='score_check_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
