# Generated by Django 4.2.5 on 2024-01-20 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0005_algorithmprediction_score_check_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='completed_gw_score',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='leaderboard_check_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
