# Generated by Django 4.2.5 on 2024-01-20 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0006_remove_leaderboard_completed_gw_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='leaderboard_check_time',
        ),
    ]
