# Generated by Django 4.2.5 on 2024-01-20 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0008_algorithmprediction_correct_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='user_recent_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
