# Generated by Django 4.2.5 on 2024-01-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0009_leaderboard_user_recent_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aileaderboard',
            name='completed_gw_score',
        ),
    ]
