# Generated by Django 4.2.5 on 2024-01-24 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prempredict', '0010_remove_aileaderboard_completed_gw_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPrivateLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('invite_url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicPrivateLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prempredict.publicprivateleaderboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publicprivateleaderboard',
            name='users',
            field=models.ManyToManyField(through='prempredict.PublicPrivateLeaderboardEntry', to=settings.AUTH_USER_MODEL),
        ),
    ]
