# Generated by Django 4.2.5 on 2024-02-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0011_publicprivateleaderboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOnly',
            fields=[
                ('createnum', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_score_update', models.PositiveIntegerField(default=0)),
                ('ai_score_update', models.PositiveIntegerField(default=0)),
                ('user_leaderboard_update', models.PositiveIntegerField(default=0)),
                ('ai_leaderboard_update', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
