# Generated by Django 4.2.5 on 2024-02-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prempredict', '0012_adminonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminonly',
            name='position_leaderboard_update',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
